<?php

namespace ContainerVo7dKBE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoneNumberValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator' shared service.
     *
     * @return \Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'odolbeau'.\DIRECTORY_SEPARATOR.'phone-number-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'Constraints'.\DIRECTORY_SEPARATOR.'PhoneNumberValidator.php';

        $container->privates['Misd\\PhoneNumberBundle\\Validator\\Constraints\\PhoneNumberValidator'] = $instance = new \Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumberValidator(($container->privates['libphonenumber\\PhoneNumberUtil'] ?? $container->getPhoneNumberUtilService()), 'ZZ', 1);

        $instance->setPropertyAccessor(($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')));

        return $instance;
    }
}
